{% set version = "4.2.3" %}

package:
  name: sourmash-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-{{ version }}.tar.gz
  sha256: 182aa079f093e691f0145e23eba7b75b7139227edc29190a89c314aa453cc084

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 0
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    # Pinning rust due to https://github.com/conda-forge/rust-feedstock/issues/73
    - rust >=1.37.0,<=1.48
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - milksnake
    - setuptools_scm >=3.2.0
    - setuptools_scm_git_archive

  run:
    - python
    - setuptools
    - screed >=1.0.5
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1
    - numpy

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/sourmash-bio/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  description: |
    This is a minimal version that avoids heavy dependencies and is as cross-platform
    as possible. For the complete version check the sourmash package in bioconda.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/sourmash-bio/sourmash
  doc_url: http://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
    - bluegenes
