{% set version = "3.5.1" %}

package:
  name: sourmash-minimal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sourmash/sourmash-{{ version }}.tar.gz
  sha256: 725d657998b2ddaafa5bef7f8902db2b53d9c2e2c476b2b7c75f868235ab8feb

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 0
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - rust >=1.37.0
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - milksnake
    - setuptools_scm >=3.2.0
    - setuptools_scm_git_archive

  run:
    - python
    - setuptools
    - screed >=1.0
    - cffi >=1.14
    - deprecation >=2.0.6
    - cachetools >=4.2.1

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/dib-lab/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  description: |
    This is a minimal version that avoids heavy dependencies and is as cross-platform
    as possible. For the complete version check the sourmash package in bioconda.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/dib-lab/sourmash
  doc_url: http://sourmash.bio/

extra:
  recipe-maintainers:
    - luizirber
    - ctb
