conda_forge_output_validation: true
linux_ppc64le:
  enabled: true
linux_aarch64:
  enabled: true
provider:
  linux_ppc64le: default
  linux_aarch64: default
github:
  branch_name: main
  tooling_branch_name: main
